version: '3.8'

services:
  # Ruby on Rails application
  web:
    build: ./cgtrader
    volumes:
      - ./cgtrader:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch

  # MySQL database
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: cgtrader
      MYSQL_DATABASE: cgtrader
      MYSQL_USER: cgtrader
      MYSQL_PASSWORD: cgtrader
    ports:
      - "3306:3306"

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
